### ISSUE TITLE
breaks with python 3.8.2

### ISSUE THREAD

**Issue by itheodoridis** [mhoogveld/check_cisco_ip_sla#10]
When using python3.7+ there is apparently an issue coming from easysnmp:
[https://github.com/kamakazikamikaze/easysnmp/issues/108](https://github.com/kamakazikamikaze/easysnmp/issues/108)
When I try to install and use check_cisco_ip_sla in Ubuntu 20.04 with python 3.8.2, 
I get this error:
`Traceback (most recent call last):
  File "./check_cisco_ip_sla.py", line 931, in <module>
    result = checker.run()
  File "./check_cisco_ip_sla.py", line 76, in run
    self.read_rtt_entries()
  File "./check_cisco_ip_sla.py", line 298, in read_rtt_entries
    rtt_ctrl_admin_entries = self.session.walk(".1.3.6.1.4.1.9.9.42.1.2.1.1")
  File "/usr/local/lib/python3.8/dist-packages/easysnmp/session.py", line 467, in walk
    interface.walk(self, varlist)
SystemError: <built-in function walk> returned NULL without setting an error`

**Comment by mhoogveld** [comment]
Thanks for reporting this issue.
I was waiting for upstream to fix this (and got distracted by life), but it looks like this easysnmp issue will not be fixed anytime soon.
In the meantime, the patch by @nerosketch can be used which works fine for me.

For example, on Ubuntu 20.04, you could do this:
```bash
sudo apt install libsnmp-dev python3-pip
git clone https://github.com/nerosketch/easysnmp.git
cd easysnmp
git checkout fix_is108

# Use with "sudo" for a system-wide install
pip3 install .
```
