### ISSUE TITLE
KeyError: 'conn_lost_occurred'

### ISSUE THREAD

**Issue by lesinigo** [mhoogveld/check_cisco_ip_sla#12]
When trying [current master](https://github.com/mhoogveld/check_cisco_ip_sla/tree/c669d7a2eea19559c55e71d5a6cca37274b2bcb1) on CentOS 7.6 with either Python 2.7.5 or Python 3.6.8, check mode will error out with:

```
$ python3 ./check_cisco_ip_sla.py -H 1.2.3.4 -v 2 -c MyCommunity --perf -m check
Traceback (most recent call last):
  File "./check_cisco_ip_sla.py", line 953, in <module>
    result = checker.run()
  File "./check_cisco_ip_sla.py", line 84, in run
    self.check()
  File "./check_cisco_ip_sla.py", line 882, in check
    if self.rtt_dict[requested_entry]["conn_lost_occurred"]:
KeyError: 'conn_lost_occurred'
```

[Line 882](https://github.com/mhoogveld/check_cisco_ip_sla/blob/c669d7a2eea19559c55e71d5a6cca37274b2bcb1/check_cisco_ip_sla.py#L882), 885 and 888 are checking for some dict keys that in my case were not present, thus giving the KeyError.

**Comment by mhoogveld** [comment]
Thanks for the report Luca.
Is it the case that all 3 keys are missing for one or more SLAs? Keys being: "conn_lost_occurred", "timeout_occurred" and "over_thres_occurred"

If that is the case, please note that the SLA will always be in OK state, so there's no use in checking it this way and another fix is needed so the plugin does not falsely report OK when the SLA is not.

**Comment by lesinigo** [comment]
That's why I specified that I did not look in the upstream code to see _why_ the keys are not there.

I was in a hurry and simply assumed that if there is any non-OK state one or more of those keys would appear in the dict and the code would do its thing correctly; before merging this PR someone should check if my assumption is indeed correct 😃 

I could try to look at it myself as soon as time permits, but I cannot promise any ETA.

**Comment by mhoogveld** [comment]
As this is device dependent, I cannot check what the right solution for this is.
If you could PM me the output of an snmpwalk, I could have a look. If you could help identify the SLA causing the issue, that might save me some time.
```snmpwalk -v 2c -On -c MyCommunity 1.2.3.4 > snmpwalk-issue-12.out```
Also the output of running the check command with the `--verbose 2` argument would help (comment out/hide your passwords)
