### ISSUE TITLE
KeyError: 'timeout_occured' thrown when checking an entry

### ISSUE THREAD

**Issue by jvalcke** [mhoogveld/check_cisco_ip_sla#4]
I get the following error message.

[vagrant@vagrant-centos64 check-scripts]$ LD_PRELOAD=/usr/local/lib/libnetsnmp.so python2.7 check_cisco_ip_sla.py -H 10.10.10.10 -c secret -m check -e 2
Traceback (most recent call last):
  File "check_cisco_ip_sla.py", line 357, in <module>
    result = checker.run()
  File "check_cisco_ip_sla.py", line 41, in run
    self.check()
  File "check_cisco_ip_sla.py", line 309, in check
    if self.rtt_dict[requested_entry]["timeout_occured"]:
KeyError: 'timeout_occured'

Changing line 309 to
                    if "timeout_occured" in self.rtt_dict[requested_entry]:
seems to fix it.

**Comment by mhoogveld** [comment]
Thank you for your report.

It appears that the rttMonCtrlOperTimeoutOccurred _should_ always be set. 
Could you send me the output of snmpwalk for .1.3.6.1.4.1.9.9.42.1.2.9.1 (or the entire tree if you like) for the device this occurs with?

**Comment by jvalcke** [comment]
@mhoogveld thanks for the feedback.

Will this do?
SNMPv2-SMI::enterprises.9.9.42.1.2.9.1.3.1 = Timeticks: (4294963603) 497 days, 2:27:16.03
SNMPv2-SMI::enterprises.9.9.42.1.2.9.1.3.2 = Timeticks: (4294963603) 497 days, 2:27:16.03
SNMPv2-SMI::enterprises.9.9.42.1.2.9.1.3.7 = Timeticks: (4294963603) 497 days, 2:27:16.03
SNMPv2-SMI::enterprises.9.9.42.1.2.9.1.9.1 = INTEGER: 2147483647
SNMPv2-SMI::enterprises.9.9.42.1.2.9.1.9.2 = INTEGER: 2147483647
SNMPv2-SMI::enterprises.9.9.42.1.2.9.1.9.7 = INTEGER: 2147483647
SNMPv2-SMI::enterprises.9.9.42.1.2.9.1.10.1 = INTEGER: 6
SNMPv2-SMI::enterprises.9.9.42.1.2.9.1.10.2 = INTEGER: 6
SNMPv2-SMI::enterprises.9.9.42.1.2.9.1.10.7 = INTEGER: 6

**Comment by jvalcke** [comment]
btw, device is a Nexus9000 C9372TX

**Comment by jvalcke** [comment]
Hmmm, I think rttMonCtrlOperTimeoutOccurred is missing.

ftp://ftp.cisco.com/pub/mibs/supportlists/nexus9000/Nexus9000MIBSupportList.html

snmpwalk -v 2c -c <community> -m CISCO-RTTMON-MIB 10.10.10.10 1.3.6.1.4.1.9.9.42.1.2.9.1.6
...
CISCO-RTTMON-MIB::rttMonCtrlOperTimeoutOccurred = No Such Object available on this agent at this OID

**Comment by mhoogveld** [comment]
It seems that that device just does not support that field.
I just went to that exact same URL.

What type of SLA did you implement in the device?

I mostly use it with type icmp-echo like so:

```
ip sla 10
 icmp-echo 1.2.3.4
 tag Test ping
ip sla schedule 10 life forever start-time now
```

If you use it in the same way, I'm not sure if enough information is available through SNMP. You could then possibly generate an SNMP trap?

Maybe I can find some more to go on if you could provide the complete SNMP tree for ciscoRttMonMIB ( .1.3.6.1.4.1.9.9.42 )

**Comment by mhoogveld** [comment]
Possibly in a private message if you like?

**Comment by jvalcke** [comment]
Thanks. I've sent you an email.
